# ===============================
# APPLICATION
# ===============================
spring.application.name=user-service

# ===============================
# DATASOURCE (PostgreSQL)
# ===============================
spring.datasource.url=${SPRING_DATASOURCE_URL:postgres-user/userdb}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

# HikariCP
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# LIQUIBASE
# ===============================
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true

# ===============================
# REDIS
# ===============================
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

# ===============================
# SERVER
# ===============================
server.port=${SERVER_PORT:8081}

# ===============================
# JWT CONFIG
# ===============================
jwt.keystore.path=${JWT_KEYSTORE_PATH:classpath:jwt-keystore.p12}
jwt.keystore.password=${JWT_KEYSTORE_PASSWORD:password-test}
jwt.keystore.alias=${JWT_KEYSTORE_ALIAS:jwt-key}

jwt.expiration-seconds=${JWT_EXPIRATION:900}

# ===============================
# SECURITY CONFIG
# ===============================
security.bcrypt.strength=${BCRYPT_STRENGTH:12}

# ===============================
# EUREKA CLIENT
# ===============================
eureka.client.service-url.defaultZone=http://eureka:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.instance.prefer-ip-address=true
eureka.instance.hostname=user-service

# ===============================
# ACTUATOR CONFIG
# ===============================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
